module.exports = {
  homepage: '',
  documentTitle: 'App',
  appRoot: '',
  sourceDirectory: 'src',
  distDirectory: 'dist',
  serverRender: false,
  production: false,
  babelQuery: null,
  webpackLoaders: [],
  publicPath: '/static/',
  htmlTemplate: '',
  webpackPerformanceHints: false,
  webpackPlugins: [],
  webpackProductionPlugins: [],
  webpackDevPlugins: [],
  postCSSPlugins: [],
  hostname: '',
  devServerHostname: 'localhost',
  devServerPort: '8080',
  devServerMiddleware: [],
  __HAS_INDEX_FILE: false,
}
